name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Exercício 1
      id: exercicio-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Exercício 1
        setup-command: ''
        command: echo "EGFR" | python exercicio_1.py
        input: ''
        expected-output: '192612'
        comparison-method: contains
        timeout: 1
        max-score: 1
    - name: Exercício 2
      id: exercicio-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Exercício 2
        setup-command: ''
        command: python exercicio_2.py
        input: ''
        expected-output: "(rs131415|rs252627)"
        comparison-method: regex
        timeout: 1
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        EXERCICIO-1_RESULTS: "${{steps.exercicio-1.outputs.result}}"
        EXERCICIO-2_RESULTS: "${{steps.exercicio-2.outputs.result}}"
      with:
        runners: exercicio-1,exercicio-2
